### ISSUE TITLE
Crash after copying linux files to folder then selecting next to list files to pick as an exe

### ISSUE THREAD

**Issue by Blad3forc3** [ruanformigoni/gameimage#130]
When i select a linux gameimage and i copy the relevant files to the linux folder then clicking next so gameimage lists the exe file to pick or script file gameimage will randomly just close. Maybe something to do with the amount of files it is reading? Also when it randomly does show a list of files and i select the script i want to run, gameimage doesnt run the script.
When i run the script without gameimage from file explorer everything runs fine.

**Comment by ruanformigoni** [comment]
Thanks for reporting this issue @Blad3forc3 ! I'll check it out.

**Comment by ruanformigoni** [comment]
Hello @Blad3forc3 , let me know if `v1.5.1` fixes this issue with crashing on selection.

**Comment by Blad3forc3** [comment]
It doesnt appear to RUan. I am trying to get the linux version of civilization v into a gameimage and after copying the files over it pauses then just closes.

The log file doesnt really give anyything interesting either

**Comment by Blad3forc3** [comment]
This is happening still.

I ran gameimage from the command line and it gives me a bit more when it closes by itself

I :: Access 'Monster-Hunter-Stories'
I :: Access 'path_dir_project'
I :: Access 'path_dir_project_root'
gameimage.rs:58: I :: Search directory '/media/ade/Temp/Temp/build/Monster-Hunter-Stories/opt/gameimage-games/Monster-Hunter-Stories/wine/drive_c'
gameimage.rs:58: I :: Exclude directory '"/media/ade/Temp/Temp/build/Monster-Hunter-Stories/opt/gameimage-games/Monster-Hunter-Stories/wine/drive_c/windows"'
gameimage.rs:58: I :: Exclude directory '"/media/ade/Temp/Temp/build/Monster-Hunter-Stories/opt/gameimage-games/Monster-Hunter-Stories/wine/drive_c/ProgramData/Microsoft/Windows"'
gameimage.rs:58: I :: Exclude directory '"/media/ade/Temp/Temp/build/Monster-Hunter-Stories/opt/gameimage-games/Monster-Hunter-Stories/wine/drive_c/users/gameimage/AppData/Local/Microsoft/Windows"'
gameimage.rs:58: I :: Exclude directory '"/media/ade/Temp/Temp/build/Monster-Hunter-Stories/opt/gameimage-games/Monster-Hunter-Stories/wine/drive_c/users/gameimage/AppData/Roaming/Microsoft/Windows"'
gameimage.rs:58: I :: Starting IPC for "/opt/gameimage/bin/gameimage-cli"
gameimage.rs:58: I :: key identifier: /opt/gameimage/bin/gameimage-cli
gameimage.rs:58: I :: Generated message_queue key: 1094189605
gameimage.rs:58: I :: Message queue id: 32810
ipc.rs:91: Frontend key is: 1094189605
ipc.rs:112: Closed existing message queue
search.rs:27: Finished reading messages
search.rs:32: Backend exited successfully
wine.rs:716: Could not read input args: No such file or directory (os error 2)
Error sending request: Broken pipe
Fatal error while communicating with the Wayland server: Broken pipe

**Comment by Blad3forc3** [comment]
This happens with wine games too if i add files to the wine directory.
It doesnt happen every time. It seems to crash when a large amount of separate files are added and it tries to read the list

**Comment by ruanformigoni** [comment]
I implemented pagination to reduce the number of items in the scroll, let me know if that fixed it. Thanks!

**Comment by Blad3forc3** [comment]
I still have the odd crash Ruan but i managed to get something interesting by running gameimage from the command line
I got this error just before it closed by itself

Fatal error while communicating with the Wayland server: Broken pipe

**Comment by Blad3forc3** [comment]
Still happening. Seems to be also when there are a large amount of files to read before displaying the exe files
